2025-07-08 23:11:18,510 - asyncio - DEBUG - Using proactor: IocpProactor
2025-07-08 23:11:18,515 - httpx - DEBUG - load_ssl_context verify=True cert=None trust_env=True http2=False
2025-07-08 23:11:18,518 - httpx - DEBUG - load_verify_locations cafile='c:\\Users\\Rachid Aitali\\OneDrive - 4JM Solutions Limited\\Desktop\\SniperX-V3-Best-Version-at-now\\.venv\\lib\\site-packages\\certifi\\cacert.pem'
2025-07-08 23:11:18,538 - httpx - DEBUG - load_ssl_context verify=True cert=None trust_env=True http2=False
2025-07-08 23:11:18,539 - httpx - DEBUG - load_verify_locations cafile='c:\\Users\\Rachid Aitali\\OneDrive - 4JM Solutions Limited\\Desktop\\SniperX-V3-Best-Version-at-now\\.venv\\lib\\site-packages\\certifi\\cacert.pem'
2025-07-08 23:11:18,560 - __main__ - INFO - Telegram Manager Bot started. Send /menu to interact.
2025-07-08 23:11:18,562 - telegram.ext.ExtBot - DEBUG - Entering: send_message
2025-07-08 23:11:18,578 - httpcore.connection - DEBUG - connect_tcp.started host='api.telegram.org' port=443 local_address=None timeout=5.0 socket_options=None
2025-07-08 23:11:23,579 - httpcore.connection - DEBUG - connect_tcp.failed exception=ConnectTimeout(TimeoutError())
2025-07-08 23:11:23,581 - __main__ - ERROR - Could not send startup message to TELEGRAM_CHAT_ID 7049055170: Timed out
2025-07-08 23:11:23,583 - telegram.ext.ExtBot - DEBUG - Entering: get_me
2025-07-08 23:11:23,586 - httpcore.connection - DEBUG - connect_tcp.started host='api.telegram.org' port=443 local_address=None timeout=5.0 socket_options=None
2025-07-08 23:11:28,315 - httpcore.connection - DEBUG - connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x0000029A8DD78E80>
2025-07-08 23:11:28,315 - httpcore.connection - DEBUG - start_tls.started ssl_context=<ssl.SSLContext object at 0x0000029A8DCE8340> server_hostname='api.telegram.org' timeout=5.0
2025-07-08 23:11:33,334 - httpcore.connection - DEBUG - start_tls.failed exception=ConnectTimeout(TimeoutError())
2025-07-08 23:11:33,335 - telegram.ext.Application - DEBUG - This Application is already shut down. Returning.
2025-07-08 23:11:33,337 - __main__ - ERROR - Error in polling: Timed out
