2025-07-08 23:13:38,610 - asyncio - DEBUG - Using proactor: IocpProactor
2025-07-08 23:13:38,614 - httpx - DEBUG - load_ssl_context verify=True cert=None trust_env=True http2=False
2025-07-08 23:13:38,617 - httpx - DEBUG - load_verify_locations cafile='c:\\Users\\Rachid Aitali\\OneDrive - 4JM Solutions Limited\\Desktop\\SniperX-V3-Best-Version-at-now\\.venv\\lib\\site-packages\\certifi\\cacert.pem'
2025-07-08 23:13:38,630 - httpx - DEBUG - load_ssl_context verify=True cert=None trust_env=True http2=False
2025-07-08 23:13:38,633 - httpx - DEBUG - load_verify_locations cafile='c:\\Users\\Rachid Aitali\\OneDrive - 4JM Solutions Limited\\Desktop\\SniperX-V3-Best-Version-at-now\\.venv\\lib\\site-packages\\certifi\\cacert.pem'
2025-07-08 23:13:38,650 - __main__ - INFO - Telegram Manager Bot started. Send /menu to interact.
2025-07-08 23:13:38,650 - telegram.ext.ExtBot - DEBUG - Entering: send_message
2025-07-08 23:13:38,657 - httpcore.connection - DEBUG - connect_tcp.started host='api.telegram.org' port=443 local_address=None timeout=5.0 socket_options=None
2025-07-08 23:13:43,653 - httpcore.connection - DEBUG - connect_tcp.failed exception=ConnectTimeout(TimeoutError())
2025-07-08 23:13:43,653 - __main__ - ERROR - Could not send startup message to TELEGRAM_CHAT_ID 7049055170: Timed out
2025-07-08 23:13:43,728 - telegram.ext.ExtBot - DEBUG - Entering: get_me
2025-07-08 23:13:43,729 - httpcore.connection - DEBUG - connect_tcp.started host='api.telegram.org' port=443 local_address=None timeout=5.0 socket_options=None
2025-07-08 23:13:47,932 - httpcore.connection - DEBUG - connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x0000023E2B9E5090>
2025-07-08 23:13:47,933 - httpcore.connection - DEBUG - start_tls.started ssl_context=<ssl.SSLContext object at 0x0000023E2B940FC0> server_hostname='api.telegram.org' timeout=5.0
2025-07-08 23:13:52,938 - httpcore.connection - DEBUG - start_tls.failed exception=ConnectTimeout(TimeoutError())
2025-07-08 23:13:52,939 - telegram.ext.Application - DEBUG - This Application is already shut down. Returning.
2025-07-08 23:13:52,940 - __main__ - ERROR - Error in polling: Timed out
